name: Hello GitHub Actions
on: [push]

jobs:
  greet:
    runs-on: ubuntu-latest
    env:
      COURSE: CloudComputing
    steps:
      - name: Say Hello
      - uses: actions/checkout@v4
      - run: echo "Hello from ${COURSE} !"
      - run: echo "I'll list files."
      - run: ls -al
